# Generated by Django 3.2.6 on 2022-03-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_id',
            field=models.UUIDField(default='fe5fce56818a41e8b7efa1a71a1f66f8', editable=False, primary_key=True, serialize=False),
        ),
    ]
