# Generated by Django 3.2.6 on 2022-03-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_alter_score_score_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_id',
            field=models.UUIDField(default='0c765506d75345e580d81c561a8bb62c', editable=False, primary_key=True, serialize=False),
        ),
    ]
