# Generated by Django 3.2.6 on 2022-03-31 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_alter_score_score_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
