# Generated by Django 3.2.6 on 2022-03-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default='bf1460c20fad4d9ea77bbb70a122352c', editable=False, primary_key=True, serialize=False),
        ),
    ]
